what I have been working on
JosephVasquez592/Project-2 pull request #9
Opened 2022-10-30 21:57 UTC by JosephVasquez592

my file organization probably isn't the best and would appreciate some constructive criticism so I can fix it

2022-10-30 22:17 UTC, mffonua requested changes
semantics in public folder

2022-10-31 04:26 UTC, mffonua approved these changes

2022-10-31 06:00 UTC, eatmorevegetabl approved these changes
Everything looks great, much better GET/POST routes than what I have so far!
The only conflicts I see is the server.js & package.json in the public folder, which Stephen asked us to not place there. Otherwise, I don't see anything wrong with it.

2022-10-31 06:01 UTC, eatmorevegetabl requested changes
Please move the package.json & server.js files outside public folder.

2022-10-31 23:53 UTC, closed without merging